backend:
  name: github
  repo: lusian-project/ncft-strategy
  branch: main
  base_url: https://ncft-strategy.pages.dev
  auth_endpoint: /admin/oauth

media_folder: /images
public_folder: /images

collections:
  - name: "content"
    label: "콘텐츠"
    folder: "/"
    create: false
    files:
      - name: "index"
        label: "사업전략 페이지"
        file: "index.html"
        fields:
          - name: "body"
            label: "전체 내용"
            widget: "markdown"
